CREATE DATABASE IF NOT EXISTS "Conssesionaire"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Spain.1252'
    LC_CTYPE = 'Spanish_Spain.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

CREATE TABLE IF NOT EXISTS Colors(
ID_Color SERIAL PRIMARY KEY,
Color VARCHAR(15) NOT NULL
);
CREATE TABLE IF NOT EXISTS Cars(
ID_Car SERIAL PRIMARY KEY,
Plate VARCHAR(30),
ID_Color INT,
CONSTRAINT FK_Color
	FOREIGN KEY(ID_Color)
	REFERENCES Colors(ID_Color),
Brand VARCHAR(30),
Model VARCHAR(30),
Speed DECIMAL
);

INSERT INTO Colors(color) VALUES ('VERDE');
INSERT INTO Cars(Plate,ID_Color,Brand,Model,Speed) VALUES 
('SP43',1,'Toyota','Auto',120.25);